### ISSUE TITLE
Add funding information, clarify computomics relation

### ISSUE THREAD

**Issue by josiahseaman** [graph-genome/graph-genome.github.io#12]
Eloi had the impression this was a pure Computomics project.  The front page needs to emphasize the open source and collaborative nature.  (Maybe the TM on logo is an issue).  We can add funding information at the bottom along with a BBSRC logo.

"Pangenome Schematic design and development research were funded through the 1001 Genomes project under grant BBSRC BB/S004661/1.
NBDC/DBCLS BioHackathon 2019 is supported by the Integrated Database Project (Ministry of Education, Culture, Sports, Science and Technology of Japan) and hosted by the National Bioscience Database Center (NBDC) and the Database Center for Life Science (DBCLS).
Computomics GmbH funded a second hackathon to implement the data pipeline in November 2019.
TY’s work was funded in part by JSPS KAKENHI (grant numbers 16H06279 and 19J21608). HM was supported by AMED under Grant Number JP19kk0205014."

![image](https://user-images.githubusercontent.com/2256148/78166890-c1509480-740a-11ea-9a97-01f7ad5820bf.png)

**Comment by Stacie-Seaman** [comment]
Additional text and BBSRC logo added.
