### ISSUE TITLE
Write Ontology for Pantograph concepts extending vg

### ISSUE THREAD

**Issue by josiahseaman** [graph-genome/graph-genome.github.io#15]
Jerven had asked me to extend https://github.com/vgteam/vg/tree/master/ontology with the new concepts of Pantograph. We'll need this to standardize building an ontology, but it's not programming itself. Take a look at https://github.com/vgteam/vg/blob/master/ontology/vg.ttl 

To implement, you'll have to read through the Pantograph specification: https://docs.google.com/document/d/1NEYkRS6Ux1w_v0Soe74FeOAMOxGHOzDun00LdjMi-74/edit#heading=h.1qmqi7nvezc3 and turn those concepts into TTL description. I've just been adding Bin and Sorting to the Specification.

This ontology will be used to build our triple store that backs the whole pipeline and will hopefully be used by other projects.

**Comment by 6br** [comment]
My understanding is that we need an ontology for the data format (currently described as JSON, but not annotated perfectly) between `component_segmentation` and `Schematize`.  Also, I will add an ontology for `odgi bin` output json.

**Comment by 6br** [comment]
Merged.
