### ISSUE TITLE
Ensure there are no redundant pages

### ISSUE THREAD

**Issue by josiahseaman** [graph-genome/graph-genome.github.io#2]
There may be redundant sections (e.g. Get Involved and Hackathon) but there should be no redundant pages.  We can possibly delete unnecessary pages.  Project.md took the content of introduction.md so I deleted the Introduction.md.  We should also have a page with lots of links to detailed documentation that will be fleshed out in pantograph.md.

**Comment by Stacie-Seaman** [comment]
I didn't find any redundant pages.
